
// This file has been generated by the GUI designer. Do not modify.
namespace FossLock.LicenseManager
{
	public partial class SettingsDialog
	{
		private global::Gtk.Table table3;
		private global::Gtk.Entry entConnectionString;
		private global::Gtk.HSeparator hseparator1;
		private global::Gtk.Label lblConnectionString;
		private global::Gtk.Label lblProviderType;
		private global::Gtk.RadioButton rdoMSSQL;
		private global::Gtk.RadioButton rdoMYSQL;
		private global::Gtk.RadioButton rdoSQLite;
		private global::Gtk.Button buttonCancel;
		private global::Gtk.Button buttonOk;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget FossLock.LicenseManager.SettingsDialog
			this.Name = "FossLock.LicenseManager.SettingsDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("FossLock Manager Settings");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.BorderWidth = ((uint)(3));
			// Internal child FossLock.LicenseManager.SettingsDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.table3 = new global::Gtk.Table (((uint)(6)), ((uint)(2)), false);
			this.table3.Name = "table3";
			this.table3.RowSpacing = ((uint)(6));
			this.table3.ColumnSpacing = ((uint)(6));
			// Container child table3.Gtk.Table+TableChild
			this.entConnectionString = new global::Gtk.Entry ();
			this.entConnectionString.CanFocus = true;
			this.entConnectionString.Name = "entConnectionString";
			this.entConnectionString.IsEditable = true;
			this.entConnectionString.InvisibleChar = '●';
			this.table3.Add (this.entConnectionString);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table3 [this.entConnectionString]));
			w2.TopAttach = ((uint)(4));
			w2.BottomAttach = ((uint)(5));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			this.table3.Add (this.hseparator1);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table3 [this.hseparator1]));
			w3.TopAttach = ((uint)(3));
			w3.BottomAttach = ((uint)(4));
			w3.RightAttach = ((uint)(2));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.lblConnectionString = new global::Gtk.Label ();
			this.lblConnectionString.Name = "lblConnectionString";
			this.lblConnectionString.LabelProp = global::Mono.Unix.Catalog.GetString ("Connection String:");
			this.table3.Add (this.lblConnectionString);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table3 [this.lblConnectionString]));
			w4.TopAttach = ((uint)(4));
			w4.BottomAttach = ((uint)(5));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.lblProviderType = new global::Gtk.Label ();
			this.lblProviderType.Name = "lblProviderType";
			this.lblProviderType.LabelProp = global::Mono.Unix.Catalog.GetString ("Provider Type:");
			this.table3.Add (this.lblProviderType);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table3 [this.lblProviderType]));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.rdoMSSQL = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Microsoft SQL Server"));
			this.rdoMSSQL.CanFocus = true;
			this.rdoMSSQL.Name = "rdoMSSQL";
			this.rdoMSSQL.DrawIndicator = true;
			this.rdoMSSQL.UseUnderline = true;
			this.rdoMSSQL.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.table3.Add (this.rdoMSSQL);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table3 [this.rdoMSSQL]));
			w6.TopAttach = ((uint)(1));
			w6.BottomAttach = ((uint)(2));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.rdoMYSQL = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Oracle MySQL"));
			this.rdoMYSQL.CanFocus = true;
			this.rdoMYSQL.Name = "rdoMYSQL";
			this.rdoMYSQL.DrawIndicator = true;
			this.rdoMYSQL.UseUnderline = true;
			this.rdoMYSQL.Group = this.rdoMSSQL.Group;
			this.table3.Add (this.rdoMYSQL);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table3 [this.rdoMYSQL]));
			w7.TopAttach = ((uint)(2));
			w7.BottomAttach = ((uint)(3));
			w7.LeftAttach = ((uint)(1));
			w7.RightAttach = ((uint)(2));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.rdoSQLite = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("SQLite"));
			this.rdoSQLite.CanFocus = true;
			this.rdoSQLite.Name = "rdoSQLite";
			this.rdoSQLite.DrawIndicator = true;
			this.rdoSQLite.UseUnderline = true;
			this.rdoSQLite.Group = this.rdoMSSQL.Group;
			this.table3.Add (this.rdoSQLite);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table3 [this.rdoSQLite]));
			w8.LeftAttach = ((uint)(1));
			w8.RightAttach = ((uint)(2));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			w1.Add (this.table3);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(w1 [this.table3]));
			w9.Position = 0;
			// Internal child FossLock.LicenseManager.SettingsDialog.ActionArea
			global::Gtk.HButtonBox w10 = this.ActionArea;
			w10.Name = "dialog1_ActionArea";
			w10.Spacing = 10;
			w10.BorderWidth = ((uint)(5));
			w10.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w11 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w10 [this.buttonCancel]));
			w11.Expand = false;
			w11.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w12 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w10 [this.buttonOk]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 580;
			this.DefaultHeight = 303;
			this.Show ();
		}
	}
}
