
// This file has been generated by the GUI designer. Do not modify.
namespace FossLock.LicenseManager
{
	public partial class MainWindow
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget FossLock.LicenseManager.MainWindow
			this.Name = "FossLock.LicenseManager.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 523;
			this.DefaultHeight = 411;
			this.Show ();
		}
	}
}
